const STORE='qamoosi_pwa_v1';
const JSON_URL='assets/data/words.json';
let data={words:[],version:0};
let state=load();
let route='home';
let selectedGrade='KG';
let quiz=null;
const grades=['KG','1','2','3','4','5','6','7','8'];
const gradeName=g=>g==='KG'?'الروضة':`الصف ${g}`;
function load(){try{return JSON.parse(localStorage.getItem(STORE))||base()}catch(e){return base()}}
function base(){return{profile:0,sound:true,profiles:[{name:'طالب 1',points:0,mastered:{},wrong:{},hard:{}}],customWords:[]}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function profile(){return state.profiles[state.profile]||state.profiles[0]}
function allWords(){return [...data.words,...state.customWords]}
function wordsForGrade(g){return allWords().filter(w=>String(w.grade)===String(g))}
function difficulty(w){let l=(w.word_en||'').length;return l<=5?'سهل':l<=8?'متوسط':'صعب'}
function play(type='tap'){if(!state.sound)return;try{let AC=window.AudioContext||window.webkitAudioContext;let c=new AC();let o=c.createOscillator();let gain=c.createGain();let f={tap:520,pop:700,good:880,bad:220,win:1040}[type]||520;o.frequency.value=f;o.type='sine';gain.gain.value=type==='bad'?0.035:0.045;o.connect(gain);gain.connect(c.destination);o.start();gain.gain.exponentialRampToValueAtTime(0.0001,c.currentTime+(type==='win'?0.28:0.09));o.stop(c.currentTime+(type==='win'?0.3:0.1))}catch(e){}}
function speak(text,lang='en-US'){play('tap');try{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang=lang;u.rate=.82;u.volume=.9;speechSynthesis.speak(u)}catch(e){toast('النطق غير مدعوم في هذا المتصفح')}}
function toast(t){let d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
async function init(){if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');await loadWords();render()}
async function loadWords(){try{let r=await fetch(JSON_URL,{cache:'no-store'});data=await r.json()}catch(e){data={version:0,words:[]}}}
async function updateWords(){try{let r=await fetch(JSON_URL+'?t='+Date.now());let j=await r.json();data=j;toast('تم تحديث القاموس');render();}catch(e){toast('تعذر التحديث، تأكد من الإنترنت')}}
function shell(html){document.getElementById('app').innerHTML=`<div class="wrap"><div class="top"><div class="ad">مساحة إعلان علوية مستقبلية</div></div>${html}</div><div class="footerAd ad">مساحة إعلان سفلية مستقبلية</div><div class="nav"><button class="${route==='home'?'on':''}" onclick="go('home')">الرئيسية</button><button class="${route==='dict'?'on':''}" onclick="go('dict')">القاموس</button><button class="${route==='cards'?'on':''}" onclick="go('cards')">البطاقات</button><button class="${route==='quiz'?'on':''}" onclick="go('quiz')">اختبار</button><button class="${route==='profile'?'on':''}" onclick="go('profile')">الملف</button></div>`}
function go(r){play();route=r;quiz=null;render()}
function render(){({home,dict,cards,quizPage,hard,stats,profilePage,addWord,settings,contact})[route==='quiz'?'quizPage':route]?.()||home()}
function home(){let p=profile();shell(`<div class="hero"><h1>قاموسي المدرسي</h1><p>مرحباً ${p.name} — المنهاج الأردني</p></div><div class="grid"><button class="tile" onclick="go('dict')"><div class="ico">🔎</div><b>القاموس</b><span>بحث ونطق ومعنى</span></button><button class="tile" onclick="go('cards')"><div class="ico">🃏</div><b>البطاقات</b><span>تعلم كلمة كلمة</span></button><button class="tile" onclick="go('quiz')"><div class="ico">✅</div><b>اختبار</b><span>اختيار من متعدد</span></button><button class="tile" onclick="go('hard')"><div class="ico">🔥</div><b>الكلمات الصعبة</b><span>أخطاء تحتاج مراجعة</span></button><button class="tile" onclick="go('stats')"><div class="ico">📊</div><b>الإحصائيات</b><span>تقدم ونقاط</span></button><button class="tile" onclick="go('addWord')"><div class="ico">➕</div><b>إضافة كلمة</b><span>كلمة جديدة يدوياً</span></button><button class="tile" onclick="go('settings')"><div class="ico">⚙️</div><b>الإعدادات</b><span>الأصوات والتحديث</span></button><button class="tile" onclick="go('contact')"><div class="ico">✉️</div><b>المطور</b><span>مراسلة بالبريد</span></button></div>`) }
function gradeSelect(){return `<select onchange="selectedGrade=this.value;render()">${grades.map(g=>`<option value="${g}" ${g==selectedGrade?'selected':''}>${gradeName(g)}</option>`).join('')}</select>`}
function dict(){let q='';let list=wordsForGrade(selectedGrade).slice(0,40);shell(`<button class="back" onclick="go('home')">رجوع</button><h2 class="title">القاموس</h2>${gradeSelect()}<input id="search" placeholder="اكتب كلمة إنجليزية أو معنى عربي" oninput="filterDict(this.value)"><div id="dictList" class="list">${dictItems(list)}</div>`)}
function dictItems(list){return list.length?list.map(w=>`<div class="card"><div class="row space"><button class="btn alt ltr" onclick="speak('${esc(w.word_en)}')">${w.word_en} 🔊</button><span class="chip">${difficulty(w)}</span></div><button class="btn" style="margin-top:10px" onclick="this.nextElementSibling.classList.toggle('hidden');play('pop')">إظهار المعنى</button><div class="meaning hidden">${w.meaning_ar}</div></div>`).join(''):`<div class="empty">لا توجد نتائج</div>`}
function filterDict(v){let s=v.toLowerCase().trim();let arr=wordsForGrade(selectedGrade).filter(w=>w.word_en.toLowerCase().includes(s)||w.meaning_ar.includes(v)).slice(0,60);document.getElementById('dictList').innerHTML=dictItems(arr)}
let cardIndex=0;
function cards(){let arr=wordsForGrade(selectedGrade);let w=arr[cardIndex%Math.max(arr.length,1)];shell(`<button class="back" onclick="go('home')">رجوع</button><h2 class="title">البطاقات التعليمية</h2>${gradeSelect()}${w?`<div class="card"><div class="chip">${cardIndex+1} / ${arr.length}</div><button class="btn alt word ltr" style="width:100%;margin:18px 0" onclick="speak('${esc(w.word_en)}')">${w.word_en}</button><button class="btn" onclick="document.getElementById('m').classList.toggle('hidden');play('pop')">إظهار المعنى</button><div id="m" class="meaning hidden">${w.meaning_ar}</div><div class="row" style="margin-top:14px"><button class="btn alt" onclick="cardIndex=Math.max(0,cardIndex-1);render()">السابق</button><button class="btn green" onclick="markMastered('${w.id}');cardIndex++;render()">أتقنتها</button><button class="btn" onclick="cardIndex++;render()">التالي</button></div></div>`:`<div class="empty">لا توجد كلمات</div>`}`)}
function markMastered(id){profile().mastered[id]=true;save();play('good')}
function quizPage(){if(!quiz)startQuiz();if(quiz.done)return quizResult();let w=quiz.items[quiz.i];let dir=quiz.dir;let question=dir==='en-ar'?w.word_en:w.meaning_ar;let opts=makeOptions(w,dir);shell(`<button class="back" onclick="go('home')">إنهاء</button><h2 class="title">اختبار ${gradeName(selectedGrade)}</h2><div class="card"><div class="row space"><span class="chip">${quiz.i+1} / ${quiz.items.length}</span><span class="chip">${dir==='en-ar'?'إنجليزي ← عربي':'عربي ← إنجليزي'}</span></div><div class="word ${dir==='en-ar'?'ltr':''}" onclick="${dir==='en-ar'?`speak('${esc(w.word_en)}')`:'play()'}">${question}</div>${opts.map(o=>`<button class="btn qopt" onclick="answer('${esc(o)}','${esc(dir==='en-ar'?w.meaning_ar:w.word_en)}','${w.id}')">${o}</button>`).join('')}</div>`)}
function startQuiz(){let items=shuffle(wordsForGrade(selectedGrade)).slice(0,20);quiz={items,i:0,correct:0,wrong:0,wrongWords:[],dir:Math.random()>.5?'en-ar':'ar-en',done:false}}
function makeOptions(w,dir){let correct=dir==='en-ar'?w.meaning_ar:w.word_en;let pool=wordsForGrade(selectedGrade).filter(x=>x.id!==w.id).map(x=>dir==='en-ar'?x.meaning_ar:x.word_en);return shuffle([correct,...shuffle(pool).slice(0,3)])}
function answer(good,real,id){if(good===real){quiz.correct++;profile().points=(profile().points||0)+0.5;profile().mastered[id]=true;play('good')}else{quiz.wrong++;profile().wrong[id]=(profile().wrong[id]||0)+1;profile().hard[id]=true;quiz.wrongWords.push(id);play('bad')}quiz.i++;quiz.dir=quiz.dir==='en-ar'?'ar-en':'en-ar';if(quiz.i>=quiz.items.length)quiz.done=true;save();setTimeout(render,160)}
function quizResult(){let total=quiz.correct+quiz.wrong;let pct=total?Math.round(quiz.correct/total*100):0;shell(`<h2 class="title">نتيجة الاختبار</h2><div class="card"><p>الأسئلة: <b>${total}</b></p><p>الصحيح: <b style="color:var(--green)">${quiz.correct}</b></p><p>الخطأ: <b style="color:var(--red)">${quiz.wrong}</b></p><p>النقاط: <b>${(quiz.correct*.5).toFixed(1)}</b></p><p>نسبة النجاح: <b>${pct}%</b></p><button class="btn" onclick="quiz=null;render()">اختبار جديد</button></div>`)}
function hard(){let ids=Object.keys(profile().hard||{});let arr=allWords().filter(w=>ids.includes(String(w.id)));shell(`<button class="back" onclick="go('home')">رجوع</button><h2 class="title">الكلمات الصعبة</h2><div class="list">${dictItems(arr)}</div>`)}
function stats(){let p=profile();let rows=grades.map(g=>{let arr=wordsForGrade(g);let m=arr.filter(w=>p.mastered[w.id]).length;let pct=arr.length?Math.round(m/arr.length*100):0;let stars=m>=100?'🏆':m>=75?'⭐⭐⭐':m>=50?'⭐⭐':m>=25?'⭐':'-';return `<div class="card"><div class="row space"><b>${gradeName(g)}</b><span>${stars}</span></div><div class="muted">${m} / ${arr.length} متقنة</div><div class="bar"><i style="width:${pct}%"></i></div></div>`}).join('');shell(`<button class="back" onclick="go('home')">رجوع</button><h2 class="title">الإحصائيات</h2><div class="card">النقاط الكلية: <b>${(p.points||0).toFixed(1)}</b></div><div class="list">${rows}</div>`)}
function profilePage(){shell(`<button class="back" onclick="go('home')">رجوع</button><h2 class="title">الملفات الشخصية</h2><div class="list">${state.profiles.map((p,i)=>`<div class="card"><div class="row space"><b>${p.name}</b><span class="chip">${(p.points||0).toFixed(1)} نقطة</span></div><div class="row" style="margin-top:10px"><button class="btn ${state.profile===i?'green':'alt'}" onclick="state.profile=${i};save();render()">اختيار</button><button class="btn alt" onclick="renameProfile(${i})">تعديل</button><button class="btn red" onclick="delProfile(${i})">حذف</button></div></div>`).join('')}</div><button class="btn" style="margin-top:14px" onclick="addProfile()">إضافة ملف</button>`)}
function addProfile(){if(state.profiles.length>=3)return toast('الحد الأعلى 3 ملفات');let n=prompt('اسم الطالب');if(n){state.profiles.push({name:n,points:0,mastered:{},wrong:{},hard:{}});save();render()}}
function renameProfile(i){let n=prompt('الاسم الجديد',state.profiles[i].name);if(n){state.profiles[i].name=n;save();render()}}
function delProfile(i){if(state.profiles.length===1)return toast('يجب أن يبقى ملف واحد');if(confirm('حذف الملف؟')){state.profiles.splice(i,1);state.profile=0;save();render()}}
function addWord(){shell(`<button class="back" onclick="go('home')">رجوع</button><h2 class="title">إضافة كلمة</h2><div class="card">${gradeSelect()}<input id="en" placeholder="English word" class="ltr"><input id="ar" placeholder="المعنى العربي"><button class="btn green" onclick="saveWord()">حفظ الكلمة</button></div>`)}
function saveWord(){let en=document.getElementById('en').value.trim().toLowerCase();let ar=document.getElementById('ar').value.trim();if(!en||!ar)return toast('أدخل الكلمة والمعنى');let id='c'+Date.now();state.customWords.push({id,grade:selectedGrade,word_en:en,meaning_ar:ar,source:'user'});save();play('good');toast('تمت إضافة الكلمة')}
function settings(){shell(`<button class="back" onclick="go('home')">رجوع</button><h2 class="title">الإعدادات</h2><div class="card"><button class="btn alt" onclick="state.sound=!state.sound;save();render()">الأصوات: ${state.sound?'مفعلة':'متوقفة'}</button><button class="btn" style="margin-top:10px" onclick="updateWords()">تحديث القاموس من JSON</button><p class="muted">الإصدار الحالي: ${data.version||0}</p></div>`)}
function contact(){shell(`<button class="back" onclick="go('home')">رجوع</button><h2 class="title">مراسلة المطور</h2><div class="card"><p>للاقتراحات أو الإبلاغ عن خطأ في كلمة:</p><a class="btn" style="display:block;text-align:center;text-decoration:none" href="mailto:yaya15112016@gmail.com?subject=قاموسي المدرسي">إرسال بريد إلكتروني</a></div>`)}
function esc(s){return String(s).replace(/'/g,"\\'")}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
init();
