(()=>{
'use strict';
const KEY='jordan_school_dictionary_pwa_v1';
const TRANS_KEY='jordan_school_dictionary_translation_cache_v1';
const ROOT=document.getElementById('app');
if(!ROOT)return;
const G=[1,2,3,4,5,6,7,8,9,10,11,12].map(String);
const STOP=new Set(('the and for with this that these those from into onto than then when where what which who whom whose why how you your yours they their theirs them there here have has had having does did done doing are was were been being can could will would shall should may might must not yes no very more most some any many much few each every both about above after again against along among around before below between during inside outside over under through without within lesson unit page pages student students teacher teachers book workbook exercise exercises activity activities read write listen look answer answers question questions complete match choose circle check tick work pair pairs group groups english arabic example examples he she him her his hers we us our ours me my mine i it its is am be do to of in on at by as or if a an up down out off too so just also only all one two three first second third next last new old make made get got go went come came say said use used using').split(' '));
let db={words:[],review:[],version:2};
let page='home';
let transCache={};
let browserTranslator=null;
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function load(){
  try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&Array.isArray(x.words))db=x}catch(e){}
  try{transCache=JSON.parse(localStorage.getItem(TRANS_KEY)||'{}')||{}}catch(e){transCache={}}
  try{
    const old=JSON.parse(localStorage.getItem('qamoosi_school_pwa_v2')||'null');
    const list=old?.words||old?.data?.words;
    if(Array.isArray(list)&&!db.words.length){
      db.words=list.map((w,i)=>({id:w.id||i+1,grade:String(w.grade||''),semester:w.semester||'',unit:w.unit||'',lesson:w.lesson||'',word_en:w.word_en||w.en||w.word||'',meaning_ar:w.meaning_ar||w.ar||w.meaning||'',example_en:w.example_en||w.sentence_en||w.exampleEn||'',example_ar:w.example_ar||w.sentence_ar||w.exampleAr||'',source_page:w.source_page||'',source_name:w.source_name||'بيانات سابقة'})).filter(w=>w.word_en);
      save();
    }
  }catch(e){}
}
function saveTrans(){try{localStorage.setItem(TRANS_KEY,JSON.stringify(transCache))}catch(e){}}
function speak(text){if(!text)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.86;speechSynthesis.speak(u)}catch(e){}}
function nav(){return `<nav class="j-nav">${[['home','🏠','الرئيسية'],['search','🔎','البحث'],['curriculum','📚','المنهاج'],['learn','🎯','التعلم'],['more','✨','المزيد']].map(x=>`<button data-page="${x[0]}" class="${page===x[0]?'active':''}">${x[1]}<br>${x[2]}</button>`).join('')}</nav>`}
function shell(body){document.body.classList.add('jordan-mode');ROOT.innerHTML=`<main class="j-shell">${body}</main>${nav()}`;ROOT.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()})}
function home(){const total=db.words.length;const grades=new Set(db.words.map(w=>w.grade).filter(Boolean)).size;shell(`<div class="j-top"><div><h1 class="j-title">القاموس المدرسي الأردني 🇯🇴</h1><p class="j-sub">يعمل على iPhone وWindows • قاموس + منهاج + مختبر كتاب</p></div><div class="j-badge">PWA متعدد الأجهزة</div></div><div class="j-stats"><div class="j-stat">${total} كلمة</div><div class="j-stat">${grades} صفوف</div></div><div class="j-grid"><article class="j-card" data-go="search"><div class="ico">🔎</div><h3>البحث الذكي</h3><p>بحث عربي/إنجليزي فوري مع النطق.</p></article><article class="j-card" data-go="curriculum"><div class="ico">📚</div><h3>المنهاج</h3><p>صف → فصل → وحدة → درس.</p></article><article class="j-card" data-go="booklab"><div class="ico">🧪</div><h3>مختبر الكتاب</h3><p>PDF → استخراج → معاني تلقائية → مراجعة → حفظ.</p></article><article class="j-card" data-go="learn"><div class="ico">🎯</div><h3>التعلم والمراجعة</h3><p>بطاقات سريعة ونطق ومراجعة.</p></article></div>`);ROOT.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>{page=x.dataset.go;render()})}
function search(){shell(`<div class="j-top"><div><h1 class="j-title">البحث الذكي</h1><p class="j-sub">English / عربي</p></div></div><div class="j-panel"><input id="jq" class="j-input" placeholder="ابدأ بكتابة كلمة..." autocomplete="off"><div id="jr" class="j-results" style="margin-top:12px"></div></div>`);const q=ROOT.querySelector('#jq'),r=ROOT.querySelector('#jr');const draw=()=>{const v=q.value.trim().toLowerCase();if(!v){r.innerHTML='<div class="j-empty">اكتب حرفًا واحدًا لبدء البحث</div>';return}const a=db.words.filter(w=>(w.word_en||'').toLowerCase().includes(v)||(w.meaning_ar||'').includes(q.value.trim())).sort((a,b)=>{const ae=(a.word_en||'').toLowerCase(),be=(b.word_en||'').toLowerCase();return (ae===v?0:ae.startsWith(v)?1:2)-(be===v?0:be.startsWith(v)?1:2)}).slice(0,80);r.innerHTML=a.length?a.map(wordCard).join(''):'<div class="j-empty">لا توجد نتائج</div>';bindSpeak()};q.oninput=draw;q.focus();draw()}
function wordCard(w){return `<div class="j-word"><button class="j-btn light j-speak" data-speak="${esc(w.word_en)}">🔊</button><div><div class="j-word-en">${esc(w.word_en)}</div><div class="j-word-ar">${esc(w.meaning_ar||'بدون معنى')}</div>${w.example_en?`<div class="j-example">${esc(w.example_en)}</div>`:''}${w.example_ar?`<div>${esc(w.example_ar)}</div>`:''}<div class="j-meta">${esc([w.grade&&`الصف ${w.grade}`,w.semester,w.unit,w.lesson,w.source_page&&`ص ${w.source_page}`].filter(Boolean).join(' • '))}</div></div>${w.example_en?`<button class="j-btn light j-speak" data-speak="${esc(w.example_en)}">🎧</button>`:'<span></span>'}</div>`}
function bindSpeak(){ROOT.querySelectorAll('.j-speak').forEach(b=>b.onclick=()=>speak(b.dataset.speak||''))}
function curriculum(){shell(`<div class="j-top"><div><h1 class="j-title">المنهاج</h1><p class="j-sub">اختر الصف</p></div></div><div class="j-grid">${G.map(g=>{const n=db.words.filter(w=>w.grade===g).length;return `<article class="j-card" data-grade="${g}"><div class="ico">📘</div><h3>الصف ${g}</h3><p>${n} كلمة محفوظة</p></article>`}).join('')}</div>`);ROOT.querySelectorAll('[data-grade]').forEach(c=>c.onclick=()=>gradeView(c.dataset.grade))}
function gradeView(g){const arr=db.words.filter(w=>w.grade===g);const sem=[...new Set(arr.map(w=>w.semester||'غير محدد'))];shell(`<div class="j-top"><div><h1 class="j-title">الصف ${g}</h1><p class="j-sub">${arr.length} كلمة</p></div><button class="j-btn light" id="back">رجوع</button></div><div class="j-grid">${sem.map(s=>`<article class="j-card" data-sem="${esc(s)}"><div class="ico">📗</div><h3>${esc(s)}</h3><p>${arr.filter(w=>(w.semester||'غير محدد')===s).length} كلمة</p></article>`).join('')}</div>`);ROOT.querySelector('#back').onclick=()=>{page='curriculum';render()};ROOT.querySelectorAll('[data-sem]').forEach(c=>c.onclick=()=>scopeView(g,c.dataset.sem))}
function scopeView(g,s){const arr=db.words.filter(w=>w.grade===g&&(w.semester||'غير محدد')===s);shell(`<div class="j-top"><div><h1 class="j-title">الصف ${g} • ${esc(s)}</h1><p class="j-sub">${arr.length} كلمة</p></div><button class="j-btn light" id="back">رجوع</button></div><div class="j-results">${arr.length?arr.map(wordCard).join(''):'<div class="j-empty">لا توجد كلمات بعد</div>'}</div>`);ROOT.querySelector('#back').onclick=()=>gradeView(g);bindSpeak()}
function learn(){const pool=[...db.words].sort(()=>Math.random()-.5).slice(0,20);shell(`<div class="j-top"><div><h1 class="j-title">التعلم</h1><p class="j-sub">بطاقات سريعة للنطق والمراجعة</p></div></div><div class="j-results">${pool.length?pool.map(wordCard).join(''):'<div class="j-empty">أضف كلمات أولًا من مختبر الكتاب</div>'}</div>`);bindSpeak()}
function more(){shell(`<div class="j-top"><div><h1 class="j-title">المزيد</h1><p class="j-sub">أدوات القاموس</p></div></div><div class="j-grid"><article class="j-card" data-go="booklab"><div class="ico">🧪</div><h3>مختبر الكتاب</h3><p>PDF → كلمات → معاني → مراجعة → حفظ</p></article><article class="j-card" id="export"><div class="ico">💾</div><h3>تصدير نسخة احتياطية</h3><p>JSON يعمل على iPhone وWindows.</p></article><article class="j-card" id="install"><div class="ico">🖥️</div><h3>التثبيت على Windows</h3><p>Edge/Chrome → Install app.</p></article></div>`);ROOT.querySelector('[data-go]').onclick=()=>{page='booklab';render()};ROOT.querySelector('#export').onclick=exportDb;ROOT.querySelector('#install').onclick=()=>alert('Windows: افتح الصفحة في Edge أو Chrome ثم اختر تثبيت التطبيق. iPhone: Safari → مشاركة → إضافة إلى الشاشة الرئيسية.')}
function exportDb(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='jordan-school-dictionary-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function validWord(raw,mid){const w=raw.trim(),l=w.toLowerCase();if(!/^[A-Za-z][A-Za-z'-]*$/.test(w)||l.length<3||l.length>28||STOP.has(l))return false;if(mid&&/^[A-Z][a-z]+$/.test(w))return false;return true}
function sentenceFor(text,word){const re=new RegExp(`\\b${word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i');return text.replace(/\s+/g,' ').split(/(?<=[.!?])\s+/).map(x=>x.trim()).find(x=>x.length>=20&&x.length<=190&&re.test(x))||''}
async function extractPdf(file,onProgress){if(!window.pdfjsLib)throw new Error('محرك PDF غير محمل');window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const data=new Uint8Array(await file.arrayBuffer());const pdf=await window.pdfjsLib.getDocument({data}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),tc=await p.getTextContent();pages.push(tc.items.map(x=>x.str).join(' '));onProgress?.(i,pdf.numPages)}return pages}
function knownMeaning(word){const key=word.toLowerCase();const hit=db.words.find(w=>(w.word_en||'').toLowerCase()===key&&(w.meaning_ar||'').trim());return hit?.meaning_ar||transCache[key]||''}
async function getBrowserTranslator(){if(browserTranslator)return browserTranslator;try{if(globalThis.Translator&&typeof globalThis.Translator.create==='function'){browserTranslator=await globalThis.Translator.create({sourceLanguage:'en',targetLanguage:'ar'});return browserTranslator}}catch(e){}return null}
async function translateWithMyMemory(text){const u='https://api.mymemory.translated.net/get?q='+encodeURIComponent(text)+'&langpair=en|ar';const c=new AbortController();const t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(u,{signal:c.signal,cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();const out=(j?.responseData?.translatedText||'').trim();if(!out||out.toLowerCase()===text.toLowerCase())return '';return out}finally{clearTimeout(t)}}
async function translateText(text){if(!text)return'';const tr=await getBrowserTranslator();if(tr){try{const out=(await tr.translate(text)).trim();if(out)return out}catch(e){}}try{return await translateWithMyMemory(text)}catch(e){return''}}
async function fillMeanings(list,progressEl){let filled=0;const missing=list.filter(c=>!c.meaning);for(let i=0;i<missing.length;i++){
  const c=missing[i];
  if(progressEl)progressEl.innerHTML=`<div class="j-progress"><div style="width:${Math.round((i+1)/Math.max(1,missing.length)*100)}%"></div></div><p>تعبئة المعاني ${i+1} من ${missing.length}...</p>`;
  const m=knownMeaning(c.word)||await translateText(c.word);
  if(m){c.meaning=m;transCache[c.word.toLowerCase()]=m;filled++}
  if(browserTranslator&&c.example_en&&!c.example_ar&&i<120){try{c.example_ar=(await browserTranslator.translate(c.example_en)).trim()}catch(e){}}
  if(!browserTranslator&&i>0&&i%20===0)await new Promise(r=>setTimeout(r,250));
}
saveTrans();return filled}
function bookLab(){shell(`<div class="j-top"><div><h1 class="j-title">مختبر الكتاب</h1><p class="j-sub">استخراج PDF + معاني عربية تلقائية + مراجعة</p></div></div><div class="j-panel"><div class="j-row"><select id="bg" class="j-select">${G.map(g=>`<option value="${g}">الصف ${g}</option>`).join('')}</select><select id="bs" class="j-select"><option>الفصل الأول</option><option>الفصل الثاني</option></select></div><div class="j-toolbar"><input id="bf" type="file" accept="application/pdf" class="j-input"><button id="ba" class="j-btn">استخراج الكلمات والمعاني</button></div><div class="j-note">يتم استبعاد الضمائر والكلمات الوظيفية والتعليمات والأرقام والرموز والأسماء الظاهرة وسط الجمل. المعاني الموجودة بالقاموس تستخدم أولًا، ثم ترجمة تلقائية للكلمات الجديدة.</div><div id="bp" style="margin-top:12px"></div><div id="br" class="j-results" style="margin-top:14px"></div></div>`);ROOT.querySelector('#ba').onclick=analyzeBook}
async function analyzeBook(){const f=ROOT.querySelector('#bf').files[0],g=ROOT.querySelector('#bg').value,s=ROOT.querySelector('#bs').value,p=ROOT.querySelector('#bp'),r=ROOT.querySelector('#br');if(!f){alert('اختر ملف PDF أولًا');return}r.innerHTML='';p.innerHTML='<div class="j-progress"><div style="width:5%"></div></div><p>جاري قراءة الكتاب...</p>';try{
  const pages=await extractPdf(f,(i,n)=>p.innerHTML=`<div class="j-progress"><div style="width:${Math.round(i/n*55)}%"></div></div><p>قراءة الصفحة ${i} من ${n}</p>`);
  const map=new Map();let unit='',lesson='';
  pages.forEach((text,pi)=>{const um=text.match(/\bUnit\s+([0-9]+|[A-Za-z]+)/i),lm=text.match(/\bLesson\s+([0-9]+|[A-Za-z]+)/i);if(um)unit=`Unit ${um[1]}`;if(lm)lesson=`Lesson ${lm[1]}`;const ms=[...text.matchAll(/[A-Za-z][A-Za-z'-]*/g)];ms.forEach((m,idx)=>{const raw=m[0],before=text.slice(Math.max(0,m.index-3),m.index),start=idx===0||/[.!?]\s*$/.test(before);if(!validWord(raw,!start))return;const key=`${unit}|${lesson}|${raw.toLowerCase()}`;const old=map.get(key);if(old){old.frequency++;if(!old.example_en)old.example_en=sentenceFor(text,raw)}else{map.set(key,{grade:g,semester:s,unit,lesson,word_en:raw.toLowerCase(),word:raw.toLowerCase(),meaning:knownMeaning(raw),example_en:sentenceFor(text,raw),example_ar:'',source_page:String(pi+1),source_name:f.name,frequency:1,selected:true})}})});
  const list=[...map.values()].filter(x=>x.frequency>=2||x.example_en).sort((a,b)=>b.frequency-a.frequency||a.word.localeCompare(b.word));
  window.__jCandidates=list;
  const before=list.filter(x=>x.meaning).length;
  const auto=await fillMeanings(list,p);
  const unresolved=list.filter(x=>!x.meaning).length;
  p.innerHTML=`<div class="j-stats"><div class="j-stat">${pages.length} صفحة</div><div class="j-stat">${list.length} كلمة مرشحة</div><div class="j-stat">${before+auto} معنى جاهز</div><div class="j-stat">${unresolved} تحتاج مراجعة</div></div>`;
  drawCandidates(list,r,p);
}catch(e){console.error(e);p.innerHTML=`<div class="j-note">تعذر تحليل الملف: ${esc(e.message||e)}</div>`}}
function drawCandidates(list,r,p){r.innerHTML=`<div class="j-toolbar"><button id="saveCand" class="j-btn green">اعتماد الكلمات المكتملة</button><button id="retryMeaning" class="j-btn">محاولة تعبئة الناقص</button><button id="allCand" class="j-btn secondary">تحديد/إلغاء الكل</button></div>${list.map((w,i)=>`<div class="j-word"><input class="j-check cand" data-i="${i}" type="checkbox" ${w.selected?'checked':''}><div><div class="j-word-en">${esc(w.word)} <button class="j-btn light j-speak" data-speak="${esc(w.word)}">🔊</button></div><input class="j-input cm" data-i="${i}" placeholder="المعنى العربي" value="${esc(w.meaning)}"><textarea class="j-textarea ce" data-i="${i}" placeholder="الجملة الإنجليزية">${esc(w.example_en)}</textarea><textarea class="j-textarea ca" data-i="${i}" placeholder="ترجمة الجملة">${esc(w.example_ar)}</textarea><div class="j-meta">${esc([w.unit,w.lesson,`ص ${w.source_page}`,`تكرار ${w.frequency}`].filter(Boolean).join(' • '))}</div></div><button class="j-btn light j-speak" data-speak="${esc(w.example_en)}">🎧</button></div>`).join('')}`;bindSpeak();r.querySelectorAll('.cm').forEach(x=>x.oninput=()=>list[+x.dataset.i].meaning=x.value);r.querySelectorAll('.ce').forEach(x=>x.oninput=()=>list[+x.dataset.i].example_en=x.value);r.querySelectorAll('.ca').forEach(x=>x.oninput=()=>list[+x.dataset.i].example_ar=x.value);r.querySelectorAll('.cand').forEach(x=>x.onchange=()=>list[+x.dataset.i].selected=x.checked);r.querySelector('#allCand').onclick=()=>{const on=list.some(x=>!x.selected);list.forEach(x=>x.selected=on);r.querySelectorAll('.cand').forEach(x=>x.checked=on)};r.querySelector('#saveCand').onclick=()=>saveCandidates(list);r.querySelector('#retryMeaning').onclick=async()=>{r.querySelector('#retryMeaning').disabled=true;await fillMeanings(list,p);drawCandidates(list,r,p)}}
function saveCandidates(list){const chosen=list.filter(x=>x.selected&&x.meaning.trim());if(!chosen.length){alert('أدخل معنى عربيًا لكلمة واحدة على الأقل');return}let added=0;chosen.forEach(w=>{const hit=db.words.find(x=>x.grade===w.grade&&x.semester===w.semester&&x.unit===w.unit&&x.lesson===w.lesson&&(x.word_en||'').toLowerCase()===w.word.toLowerCase());const obj={grade:w.grade,semester:w.semester,unit:w.unit,lesson:w.lesson,word_en:w.word,meaning_ar:w.meaning,example_en:w.example_en,example_ar:w.example_ar,source_page:w.source_page,source_name:w.source_name};if(hit){Object.assign(hit,obj)}else{db.words.push({...obj,id:Date.now()+Math.random()});added++}});save();alert(`تم الحفظ. كلمات جديدة: ${added}`);page='curriculum';render()}
function render(){if(page==='home')home();else if(page==='search')search();else if(page==='curriculum')curriculum();else if(page==='learn')learn();else if(page==='more')more();else if(page==='booklab')bookLab();else home()}
load();setTimeout(render,0);
})();
