from pathlib import Path
import re
p=Path('jordan/jordan-pwa.js')
s=p.read_text(encoding='utf-8')

# Replace quiz setup + runner created by the base v352 learning upgrade.
# Include the original reviewCards signature in the match so reruns cannot
# produce a duplicated `(index=0)` suffix.
pat=re.compile(r"function quizSetup\(\)\{.*?\}\nfunction reviewCards\(index=0\)",re.S)
m=pat.search(s)
if not m: raise SystemExit('v352 quiz block not found')

new=r'''function ensureProgress(){db.review=Array.isArray(db.review)?db.review:[];db.mastered=Array.isArray(db.mastered)?db.mastered:[];db.studied=Array.isArray(db.studied)?db.studied:[];db.difficult=Array.isArray(db.difficult)?db.difficult:[];db.wrongCounts=(db.wrongCounts&&typeof db.wrongCounts==='object')?db.wrongCounts:{};db.points=Number(db.points||0)}
function difficultyScore(w){ensureProgress();const id=String(w.id);return Number(db.wrongCounts[id]||0)*10+(db.difficult.map(String).includes(id)?20:0)-(db.mastered.map(String).includes(id)?12:0)}
function smartReviewPool(){ensureProgress();return [...db.words].filter(w=>w.word_en&&w.meaning_ar).sort((a,b)=>{const score=w=>Number(db.wrongCounts[String(w.id)]||0)*10+(db.difficult.map(String).includes(String(w.id))?20:0)+(!db.mastered.map(String).includes(String(w.id))?5:0)+(w.example_en&&w.example_ar?2:0);return score(b)-score(a)}).slice(0,60)}
function unitOptions(grade){return [...new Set(learningPool(grade).map(w=>String(w.unit||'').trim()).filter(Boolean))].sort()}
function pageNum(w){const m=String(w.source_page||'').match(/\d+/);return m?Number(m[0]):999999}
function buildQuizQuestions(grade,mode,unit,count){ensureProgress();let list=[];if(mode==='comprehensive'){list=[...db.words].filter(w=>w.word_en&&w.meaning_ar).sort((a,b)=>(Number(a.grade||99)-Number(b.grade||99))||(Number(a.id)-Number(b.id)))}else if(mode==='pdf'){list=learningPool(grade).filter(w=>String(w.source_page||'').trim()).sort((a,b)=>pageNum(a)-pageNum(b)||(Number(a.id)-Number(b.id)))}else if(mode==='unit'){list=learningPool(grade).filter(w=>String(w.unit||'')===unit)}else if(mode==='easy'){list=[...learningPool(grade)].sort((a,b)=>difficultyScore(a)-difficultyScore(b))}else if(mode==='studied'){list=learningPool(grade).filter(w=>db.studied.map(String).includes(String(w.id)))}else{list=[...learningPool(grade)].sort(()=>Math.random()-.5)}return count>0?list.slice(0,count):list}
function quizSetup(){ensureProgress();shell(`${learningHeader('اختبار AI متكيف','اختر نوع الاختبار وعدد الأسئلة')}<div class="j-panel"><div class="j-row">${gradePicker()}<select id="quizMode" class="j-select"><option value="random">عشوائي</option><option value="pdf">حسب ترتيب ظهور الكلمات في PDF</option><option value="unit">حسب الوحدة</option><option value="easy">حسب السهولة</option><option value="studied">حسب الكلمات المدروسة على الجهاز</option><option value="comprehensive">شامل - جميع الصفوف</option></select></div><div class="j-row" style="margin-top:10px"><select id="quizUnit" class="j-select" style="display:none"></select><select id="quizCount" class="j-select"><option value="10">10 أسئلة</option><option value="20" selected>20 سؤالاً</option><option value="40">40 سؤالاً</option><option value="0">كل الكلمات المتاحة</option></select></div><div id="quizHint" class="j-note" style="margin-top:12px">اختبار عشوائي من الصف المختار.</div><button id="beginQuiz" class="j-btn" style="margin-top:16px;width:100%">ابدأ الاختبار</button></div>`);ROOT.querySelector('#learnBack').onclick=learn;const grade=ROOT.querySelector('#learnGrade'),mode=ROOT.querySelector('#quizMode'),unit=ROOT.querySelector('#quizUnit'),hint=ROOT.querySelector('#quizHint');const refresh=()=>{const m=mode.value;grade.disabled=m==='comprehensive';unit.style.display=m==='unit'?'block':'none';if(m==='unit'){const u=unitOptions(grade.value);unit.innerHTML=u.length?u.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join(''):'<option value="">لا توجد وحدات</option>'}hint.textContent={random:'عشوائي من الصف المحدد.',pdf:'يحافظ على ترتيب الصفحات وترتيب الكلمات المستخرجة من PDF.',unit:'يختبر كلمات وحدة واحدة فقط.',easy:'يرتب من الأسهل إلى الأصعب اعتمادًا على أخطائك وتقدمك.',studied:'يختبر فقط الكلمات التي سبق أن درستها.',comprehensive:'اختبار شامل من جميع الصفوف.'}[m]||''};mode.onchange=refresh;grade.onchange=refresh;refresh();ROOT.querySelector('#beginQuiz').onclick=()=>{const m=mode.value,u=unit.value,c=Number(ROOT.querySelector('#quizCount').value),g=grade.value;if(m==='unit'&&!u){alert('اختر وحدة تحتوي كلمات أولًا');return}const q=buildQuizQuestions(g,m,u,c);if(!q.length){alert(m==='pdf'?'لا توجد كلمات مرتبطة بصفحات PDF في هذا الصف بعد':m==='studied'?'افتح بعض الكلمات وادرسها أولًا':'لا توجد كلمات مناسبة لهذا الاختبار');return}runQuiz(g,m,u,c,0,0,q)}}
function runQuiz(grade,mode,unit,count,i=0,score=0,questions=[]){ensureProgress();if(i>=questions.length){shell(`${learningHeader('نتيجة الاختبار','الاختبار المتكيف يحفظ أخطاءك للمراجعة القادمة')}<div class="j-panel" style="text-align:center"><div style="font-size:54px;font-weight:800">${score} / ${questions.length}</div><div class="j-stats" style="margin-top:16px"><div class="j-stat">${Math.round(score/questions.length*100)}%</div><div class="j-stat">${Math.round(db.points*10)/10} نقطة</div><div class="j-stat">${db.review.length} للمراجعة</div></div><div class="j-toolbar" style="justify-content:center;margin-top:18px"><button id="again" class="j-btn">إعادة بنفس الإعدادات</button><button id="newQuiz" class="j-btn secondary">اختبار جديد</button><button id="toReview" class="j-btn secondary">مراجعة AI</button></div></div>`);ROOT.querySelector('#learnBack').onclick=learn;ROOT.querySelector('#again').onclick=()=>runQuiz(grade,mode,unit,count,0,0,buildQuizQuestions(grade,mode,unit,count));ROOT.querySelector('#newQuiz').onclick=quizSetup;ROOT.querySelector('#toReview').onclick=()=>reviewCards(0,true);return}const w=questions[i];const source=mode==='comprehensive'?learningPool('all'):learningPool(grade);const distract=[...source].filter(x=>String(x.id)!==String(w.id)&&x.meaning_ar!==w.meaning_ar).sort(()=>Math.random()-.5).slice(0,3);const opts=[w,...distract].sort(()=>Math.random()-.5);shell(`${learningHeader('اختبار AI متكيف',`السؤال ${i+1} من ${questions.length}`)}<div class="j-panel"><div class="j-stats"><div class="j-stat">${score} صحيح</div><div class="j-stat">${db.wrongCounts[String(w.id)]||0} أخطاء سابقة</div></div><div style="text-align:center"><div class="j-word-en" style="font-size:36px;margin:18px">${esc(w.word_en)} <button class="j-btn light j-speak" data-speak="${esc(w.word_en)}">🔊</button></div><div class="j-grid">${opts.map(o=>`<button class="j-card quizOpt" data-id="${esc(String(o.id))}" style="border:0;text-align:center"><h3>${esc(o.meaning_ar)}</h3></button>`).join('')}</div></div></div>`);ROOT.querySelector('#learnBack').onclick=learn;ROOT.querySelectorAll('.quizOpt').forEach(b=>b.onclick=()=>{const id=String(w.id),ok=id===b.dataset.id;if(!db.studied.map(String).includes(id))db.studied.push(w.id);if(ok){db.points+=0.5;if(!db.mastered.map(String).includes(id))db.mastered.push(w.id);db.difficult=db.difficult.filter(x=>String(x)!==id);db.review=db.review.filter(x=>String(x)!==id)}else{db.wrongCounts[id]=Number(db.wrongCounts[id]||0)+1;if(!db.difficult.map(String).includes(id))db.difficult.push(w.id);if(!db.review.map(String).includes(id))db.review.push(w.id);db.mastered=db.mastered.filter(x=>String(x)!==id)}save();runQuiz(grade,mode,unit,count,i+1,score+(ok?1:0),questions)});bindSpeak()}
function reviewCards(index=0,smart=false)'''
s=s[:m.start()]+new+s[m.end():]
# Modify reviewCards pool to support AI-ranked review when smart=true.
s=s.replace("const pool=db.review.map(id=>db.words.find(w=>String(w.id)===String(id))).filter(Boolean);","const pool=smart?smartReviewPool():db.review.map(id=>db.words.find(w=>String(w.id)===String(id))).filter(Boolean);",1)
# Make training card explicitly Android-parity AI review.
s=s.replace("<h3>مراجعة الكلمات</h3><p>راجع الكلمات التي اخترت أنها تحتاج مراجعة.</p>","<h3>مراجعة AI</h3><p>ترتيب ذكي حسب أخطائك والكلمات الصعبة وغير المتقنة.</p>",1)
s=s.replace("ROOT.querySelector('#reviewStart').onclick=()=>reviewCards()","ROOT.querySelector('#reviewStart').onclick=()=>reviewCards(0,true)",1)
p.write_text(s,encoding='utf-8')
print('v352 Android parity adaptive quiz applied')
