from pathlib import Path
import re
p=Path('jordan/jordan-pwa.js')
s=p.read_text(encoding='utf-8')

# Insert profile/progress helpers after save().
anchor="function save(){localStorage.setItem(KEY,JSON.stringify(db))}"
if anchor not in s: raise SystemExit('save anchor missing')
helpers=r'''function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function progressSnapshot(){ensureProgress();return {review:[...db.review],mastered:[...db.mastered],studied:[...db.studied],difficult:[...db.difficult],wrongCounts:{...db.wrongCounts},points:Number(db.points||0),lastIndexByGrade:{...(db.lastIndexByGrade||{})}}}
function applyProgress(x={}){db.review=Array.isArray(x.review)?x.review:[];db.mastered=Array.isArray(x.mastered)?x.mastered:[];db.studied=Array.isArray(x.studied)?x.studied:[];db.difficult=Array.isArray(x.difficult)?x.difficult:[];db.wrongCounts=(x.wrongCounts&&typeof x.wrongCounts==='object')?x.wrongCounts:{};db.points=Number(x.points||0);db.lastIndexByGrade=(x.lastIndexByGrade&&typeof x.lastIndexByGrade==='object')?x.lastIndexByGrade:{}}
function ensureProfiles(){ensureProgress();if(!Array.isArray(db.profiles)||!db.profiles.length){db.profiles=[{id:1,name:'الطالب 1'}];db.activeProfile=1;db.profileProgress={'1':progressSnapshot()}}db.profileProgress=(db.profileProgress&&typeof db.profileProgress==='object')?db.profileProgress:{};db.activeProfile=Number(db.activeProfile||db.profiles[0].id||1);if(!db.profileProgress[String(db.activeProfile)])db.profileProgress[String(db.activeProfile)]=progressSnapshot()}
function persistActiveProgress(){ensureProfiles();db.profileProgress[String(db.activeProfile)]=progressSnapshot();save()}
function switchProfile(id){ensureProfiles();persistActiveProgress();db.activeProfile=Number(id);applyProgress(db.profileProgress[String(id)]||{});save();render()}
'''
s=s.replace(anchor,helpers,1)

# Mark studied and preserve last card index in quick cards.
s=s.replace("function quickCards(grade='all',index=0,reveal=false){const pool=learningPool(grade);", "function quickCards(grade='all',index=null,reveal=false){ensureProgress();db.lastIndexByGrade=(db.lastIndexByGrade&&typeof db.lastIndexByGrade==='object')?db.lastIndexByGrade:{};const pool=learningPool(grade);if(index===null)index=Number(db.lastIndexByGrade[grade]||0);")
s=s.replace("index=Math.max(0,Math.min(index,pool.length-1));const w=pool[index];", "index=Math.max(0,Math.min(index,pool.length-1));db.lastIndexByGrade[grade]=index;const w=pool[index];if(!db.studied.map(String).includes(String(w.id)))db.studied.push(w.id);persistActiveProgress();")
s=s.replace("sel.onchange=()=>quickCards(sel.value,0,false)","sel.onchange=()=>quickCards(sel.value,null,false)")

# Replace more() with richer Android-parity menu.
more=re.search(r"function more\(\)\{.*?\}\nfunction exportDb",s,re.S)
if not more: raise SystemExit('more() not found')
new_more=r'''function more(){ensureProfiles();shell(`<div class="j-top"><div><h1 class="j-title">المزيد</h1><p class="j-sub">أدوات Easy English AI</p></div></div><div class="j-grid"><article class="j-card" data-go="booklab"><div class="ico">🧪</div><h3>استوديو AI للكتاب</h3><p>PDF → كلمات → مراجعة → حفظ</p></article><article class="j-card" id="stats"><div class="ico">📊</div><h3>التقدم والإحصائيات</h3><p>النقاط، المتقنة، الصعبة وتقدم كل صف.</p></article><article class="j-card" id="sentences"><div class="ico">💬</div><h3>الجمل التعليمية</h3><p>جميع الجمل مع النطق والترجمة.</p></article><article class="j-card" id="profiles"><div class="ico">👥</div><h3>الطلاب</h3><p>حتى 3 ملفات مستقلة لكل طالب.</p></article><article class="j-card" id="export"><div class="ico">💾</div><h3>تصدير نسخة احتياطية</h3><p>JSON يشمل الكلمات والتقدم والطلاب.</p></article><article class="j-card" id="install"><div class="ico">🖥️</div><h3>التثبيت على Windows</h3><p>افتح من Edge أو Chrome ثم اختر Install app.</p></article></div>`);ROOT.querySelector('[data-go]').onclick=()=>{page='booklab';render()};ROOT.querySelector('#stats').onclick=statsPage;ROOT.querySelector('#sentences').onclick=sentencesPage;ROOT.querySelector('#profiles').onclick=profilesPage;ROOT.querySelector('#export').onclick=exportDb;ROOT.querySelector('#install').onclick=()=>alert('على Windows: افتح الصفحة في Edge أو Chrome ثم من شريط العنوان اختر تثبيت التطبيق / Install app. على iPhone: Safari → مشاركة → إضافة إلى الشاشة الرئيسية.')}
function statsPage(){ensureProfiles();const total=db.words.length,mastered=new Set(db.mastered.map(String)),difficult=new Set(db.difficult.map(String));shell(`${learningHeader('التقدم والإحصائيات','ملخص واضح للتقدم لكل طالب')}<div class="j-stats"><div class="j-stat">${Math.round(db.points*10)/10} نقطة</div><div class="j-stat">${mastered.size} متقنة</div><div class="j-stat">${difficult.size} صعبة</div><div class="j-stat">${total} كلمة</div></div><div class="j-results">${G.map(g=>{const words=db.words.filter(w=>w.grade===g);const done=words.filter(w=>mastered.has(String(w.id))).length;const pct=words.length?Math.round(done/words.length*100):0;return `<div class="j-card"><h3>الصف ${g}</h3><div class="j-progress"><div style="width:${pct}%"></div></div><p>${done} من ${words.length} • ${pct}%</p></div>`}).join('')}</div>`);ROOT.querySelector('#learnBack').onclick=()=>{page='more';render()}}
function sentencesPage(){const items=db.words.filter(w=>w.example_en||w.example_ar);shell(`${learningHeader('الجمل التعليمية',`${items.length} جملة متاحة`)}<div class="j-results">${items.length?items.map(w=>`<div class="j-word"><button class="j-btn light j-speak" data-speak="${esc(w.word_en)}">🔊</button><div><div class="j-word-en">${esc(w.word_en)}</div>${w.example_en?`<div class="j-example">${esc(w.example_en)}</div>`:''}${w.example_ar?`<div>${esc(w.example_ar)}</div>`:''}</div>${w.example_en?`<button class="j-btn light j-speak" data-speak="${esc(w.example_en)}">🎧</button>`:'<span></span>'}</div>`).join(''):'<div class="j-empty">لا توجد جمل بعد</div>'}</div>`);ROOT.querySelector('#learnBack').onclick=()=>{page='more';render()};bindSpeak()}
function profilesPage(){ensureProfiles();const active=Number(db.activeProfile);shell(`${learningHeader('الطلاب','لكل طالب تقدمه وأخطاؤه ونقاطه بشكل مستقل')}<div class="j-results">${db.profiles.map(p=>`<div class="j-card" data-profile="${p.id}"><h3>${esc(p.name)}</h3><p>${Number(p.id)===active?'الملف النشط ✓':'اضغط للتبديل'}</p></div>`).join('')}</div>${db.profiles.length<3?'<button id="addProfile" class="j-btn" style="width:100%;margin-top:12px">إضافة طالب</button>':''}`);ROOT.querySelector('#learnBack').onclick=()=>{page='more';render()};ROOT.querySelectorAll('[data-profile]').forEach(x=>x.onclick=()=>switchProfile(Number(x.dataset.profile)));const add=ROOT.querySelector('#addProfile');if(add)add.onclick=()=>{ensureProfiles();const ids=[1,2,3],id=ids.find(x=>!db.profiles.some(p=>Number(p.id)===x));if(!id)return;persistActiveProgress();db.profiles.push({id,name:`الطالب ${id}`});db.profileProgress[String(id)]={review:[],mastered:[],studied:[],difficult:[],wrongCounts:{},points:0,lastIndexByGrade:{}};save();profilesPage()}}
function exportDb'''
s=s[:more.start()]+new_more+s[more.end():]

p.write_text(s,encoding='utf-8')
print('v352 Android product parity extras applied')
