from pathlib import Path
import re

p=Path('jordan/jordan-pwa.js')
s=p.read_text(encoding='utf-8')

old=re.search(r"function learn\(\)\{.*?\}\nfunction more",s,re.S)
if not old:
    raise SystemExit('learn() block not found')

new=r'''function learningPool(grade='all'){return db.words.filter(w=>grade==='all'||w.grade===grade).filter(w=>w.word_en&&w.meaning_ar)}
function learningHeader(title,sub){return `<div class="j-top"><div><h1 class="j-title">${title}</h1><p class="j-sub">${sub}</p></div><button class="j-btn light" id="learnBack">رجوع</button></div>`}
function learn(){const reviewCount=Array.isArray(db.review)?db.review.length:0;const mastered=Array.isArray(db.mastered)?db.mastered.length:0;shell(`<div class="j-top"><div><h1 class="j-title">تدريب</h1><p class="j-sub">تعلم، اختبر نفسك، وراجع نقاط ضعفك</p></div></div><div class="j-stats"><div class="j-stat">${db.words.length} كلمة</div><div class="j-stat">${reviewCount} تحتاج مراجعة</div><div class="j-stat">${mastered} أتقنتها</div></div><div class="j-grid"><article class="j-card" id="quickCards"><div class="ico">🃏</div><h3>بطاقات سريعة</h3><p>كلمة، معنى، جملة، ترجمة، نطق، السابق والتالي.</p></article><article class="j-card" id="quizStart"><div class="ico">🧠</div><h3>اختبار الكلمات</h3><p>10 أسئلة عشوائية مع نتيجة فورية.</p></article><article class="j-card" id="reviewStart"><div class="ico">🔁</div><h3>مراجعة الكلمات</h3><p>راجع الكلمات التي اخترت أنها تحتاج مراجعة.</p></article></div>`);ROOT.querySelector('#quickCards').onclick=()=>quickCards();ROOT.querySelector('#quizStart').onclick=()=>quizSetup();ROOT.querySelector('#reviewStart').onclick=()=>reviewCards()}
function gradePicker(label='اختر الصف'){return `<select id="learnGrade" class="j-select"><option value="all">كل الصفوف</option>${G.map(g=>`<option value="${g}">الصف ${g}</option>`).join('')}</select>`}
function quickCards(grade='all',index=0,reveal=false){const pool=learningPool(grade);if(!pool.length){shell(`${learningHeader('بطاقات سريعة','لا توجد كلمات مكتملة في هذا النطاق')}<div class="j-empty">اختر صفًا آخر أو أضف كلمات بمعانٍ.</div>`);ROOT.querySelector('#learnBack').onclick=learn;return}index=Math.max(0,Math.min(index,pool.length-1));const w=pool[index];shell(`${learningHeader('بطاقات سريعة','تعلم كلمة واحدة بتركيز كامل')}<div class="j-panel"><div class="j-row">${gradePicker()}<div class="j-stat">${index+1} من ${pool.length}</div></div><div style="text-align:center;padding:22px 8px"><div class="j-word-en" style="font-size:38px;margin-bottom:10px">${esc(w.word_en)} <button class="j-btn light j-speak" data-speak="${esc(w.word_en)}">🔊</button></div>${reveal?`<div class="j-word-ar" style="font-size:24px;margin:12px 0">${esc(w.meaning_ar)}</div>${w.example_en?`<div class="j-example" style="font-size:18px;margin-top:18px">${esc(w.example_en)} <button class="j-btn light j-speak" data-speak="${esc(w.example_en)}">🎧 اسمع الجملة</button></div>`:''}${w.example_ar?`<div style="margin-top:10px;font-size:17px">${esc(w.example_ar)}</div>`:''}`:`<button id="revealCard" class="j-btn" style="margin:18px auto">إظهار المعنى والجملة</button>`}<div class="j-meta" style="margin-top:18px">${esc([w.grade&&`الصف ${w.grade}`,w.semester,w.unit,w.lesson].filter(Boolean).join(' • '))}</div></div><div class="j-toolbar" style="justify-content:center"><button id="prevCard" class="j-btn secondary" ${index===0?'disabled':''}>السابق</button><button id="needReview" class="j-btn secondary">تحتاج مراجعة</button><button id="mastered" class="j-btn green">أتقنتها</button><button id="nextCard" class="j-btn" ${index===pool.length-1?'disabled':''}>التالي</button></div></div>`);ROOT.querySelector('#learnBack').onclick=learn;const sel=ROOT.querySelector('#learnGrade');sel.value=grade;sel.onchange=()=>quickCards(sel.value,0,false);const rev=ROOT.querySelector('#revealCard');if(rev)rev.onclick=()=>quickCards(grade,index,true);ROOT.querySelector('#prevCard').onclick=()=>quickCards(grade,index-1,false);ROOT.querySelector('#nextCard').onclick=()=>quickCards(grade,index+1,false);ROOT.querySelector('#needReview').onclick=()=>{db.review=Array.isArray(db.review)?db.review:[];if(!db.review.includes(w.id))db.review.push(w.id);db.mastered=Array.isArray(db.mastered)?db.mastered.filter(id=>id!==w.id):[];save();quickCards(grade,Math.min(index+1,pool.length-1),false)};ROOT.querySelector('#mastered').onclick=()=>{db.mastered=Array.isArray(db.mastered)?db.mastered:[];if(!db.mastered.includes(w.id))db.mastered.push(w.id);db.review=Array.isArray(db.review)?db.review.filter(id=>id!==w.id):[];save();quickCards(grade,Math.min(index+1,pool.length-1),false)};bindSpeak()}
function quizSetup(){shell(`${learningHeader('اختبار الكلمات','اختر الصف ثم ابدأ')}<div class="j-panel"><div class="j-row">${gradePicker()}<button id="beginQuiz" class="j-btn">ابدأ الاختبار</button></div><div class="j-note">10 أسئلة. اختر المعنى العربي الصحيح للكلمة الإنجليزية.</div></div>`);ROOT.querySelector('#learnBack').onclick=learn;ROOT.querySelector('#beginQuiz').onclick=()=>runQuiz(ROOT.querySelector('#learnGrade').value)}
function runQuiz(grade='all',i=0,score=0,questions=null){const source=learningPool(grade);if(source.length<4){alert('نحتاج 4 كلمات مكتملة على الأقل لهذا الاختبار');return}if(!questions)questions=[...source].sort(()=>Math.random()-.5).slice(0,Math.min(10,source.length));if(i>=questions.length){shell(`${learningHeader('نتيجة الاختبار','أحسنت، يمكنك إعادة المحاولة أو مراجعة الكلمات')}<div class="j-panel" style="text-align:center"><div style="font-size:54px;font-weight:800">${score} / ${questions.length}</div><p class="j-sub">${score===questions.length?'ممتاز! أتقنت الاختبار بالكامل.':score>=questions.length*.7?'نتيجة جيدة جدًا.':'راجع الكلمات التي أخطأت بها ثم حاول مرة أخرى.'}</p><div class="j-toolbar" style="justify-content:center"><button id="again" class="j-btn">اختبار جديد</button><button id="toReview" class="j-btn secondary">مراجعة الكلمات</button></div></div>`);ROOT.querySelector('#learnBack').onclick=learn;ROOT.querySelector('#again').onclick=()=>runQuiz(grade);ROOT.querySelector('#toReview').onclick=reviewCards;return}const w=questions[i];const distract=[...source].filter(x=>x.id!==w.id&&x.meaning_ar!==w.meaning_ar).sort(()=>Math.random()-.5).slice(0,3);const opts=[w,...distract].sort(()=>Math.random()-.5);shell(`${learningHeader('اختبار الكلمات',`السؤال ${i+1} من ${questions.length}`)}<div class="j-panel"><div style="text-align:center"><div class="j-word-en" style="font-size:36px;margin:18px">${esc(w.word_en)} <button class="j-btn light j-speak" data-speak="${esc(w.word_en)}">🔊</button></div><div class="j-grid">${opts.map(o=>`<button class="j-card quizOpt" data-id="${esc(String(o.id))}" style="border:0;text-align:center"><h3>${esc(o.meaning_ar)}</h3></button>`).join('')}</div><div class="j-meta">النتيجة الحالية: ${score}</div></div></div>`);ROOT.querySelector('#learnBack').onclick=learn;ROOT.querySelectorAll('.quizOpt').forEach(b=>b.onclick=()=>{const ok=String(w.id)===b.dataset.id;if(!ok){db.review=Array.isArray(db.review)?db.review:[];if(!db.review.includes(w.id))db.review.push(w.id);save()}runQuiz(grade,i+1,score+(ok?1:0),questions)});bindSpeak()}
function reviewCards(index=0){db.review=Array.isArray(db.review)?db.review:[];const pool=db.review.map(id=>db.words.find(w=>String(w.id)===String(id))).filter(Boolean);if(!pool.length){shell(`${learningHeader('مراجعة الكلمات','لا توجد كلمات معلّمة للمراجعة')}<div class="j-panel" style="text-align:center"><div style="font-size:50px">🎉</div><h3>قائمة المراجعة فارغة</h3><p>من البطاقات السريعة اختر «تحتاج مراجعة» لأي كلمة تريد العودة إليها.</p><button id="openCards" class="j-btn">فتح البطاقات السريعة</button></div>`);ROOT.querySelector('#learnBack').onclick=learn;ROOT.querySelector('#openCards').onclick=()=>quickCards();return}index=Math.max(0,Math.min(index,pool.length-1));const w=pool[index];shell(`${learningHeader('مراجعة الكلمات',`${index+1} من ${pool.length}`)}<div class="j-panel" style="text-align:center"><div class="j-word-en" style="font-size:36px;margin:12px">${esc(w.word_en)} <button class="j-btn light j-speak" data-speak="${esc(w.word_en)}">🔊</button></div><div class="j-word-ar" style="font-size:23px;margin:10px">${esc(w.meaning_ar)}</div>${w.example_en?`<div class="j-example">${esc(w.example_en)} <button class="j-btn light j-speak" data-speak="${esc(w.example_en)}">🎧</button></div>`:''}${w.example_ar?`<div style="margin-top:8px">${esc(w.example_ar)}</div>`:''}<div class="j-toolbar" style="justify-content:center;margin-top:20px"><button id="reviewPrev" class="j-btn secondary" ${index===0?'disabled':''}>السابق</button><button id="reviewDone" class="j-btn green">أتقنتها الآن</button><button id="reviewNext" class="j-btn" ${index===pool.length-1?'disabled':''}>التالي</button></div></div>`);ROOT.querySelector('#learnBack').onclick=learn;ROOT.querySelector('#reviewPrev').onclick=()=>reviewCards(index-1);ROOT.querySelector('#reviewNext').onclick=()=>reviewCards(index+1);ROOT.querySelector('#reviewDone').onclick=()=>{db.review=db.review.filter(id=>String(id)!==String(w.id));db.mastered=Array.isArray(db.mastered)?db.mastered:[];if(!db.mastered.includes(w.id))db.mastered.push(w.id);save();reviewCards(Math.min(index,pool.length-2))};bindSpeak()}
function more'''
s=s[:old.start()]+new+s[old.end():]

# bump PWA refs v351 -> v352
idx=Path('jordan/index.html')
i=idx.read_text(encoding='utf-8').replace('?v=351','?v=352')
idx.write_text(i,encoding='utf-8')
s=s.replace("assets/data/words.json?v=351","assets/data/words.json?v=352")
p.write_text(s,encoding='utf-8')

sw=Path('jordan/sw.js')
w=sw.read_text(encoding='utf-8').replace('easy-english-ai-pwa-v351-content','easy-english-ai-pwa-v352-learning').replace('?v=351','?v=352')
sw.write_text(w,encoding='utf-8')
print('v352 learning experience applied')
